/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseError
 */
export interface BaseError {
    /**
     * 
     * @type {number}
     * @memberof BaseError
     */
    code: number;
}

/**
 * Check if a given object implements the BaseError interface.
 */
export function instanceOfBaseError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function BaseErrorFromJSON(json: any): BaseError {
    return BaseErrorFromJSONTyped(json, false);
}

export function BaseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function BaseErrorToJSON(value?: BaseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

