/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SystemRef } from './SystemRef';
import {
    SystemRefFromJSON,
    SystemRefFromJSONTyped,
    SystemRefToJSON,
} from './SystemRef';

/**
 * 
 * @export
 * @interface ConfigsRequest
 */
export interface ConfigsRequest {
    /**
     * 
     * @type {Array<SystemRef>}
     * @memberof ConfigsRequest
     */
    selectedSystems: Array<SystemRef>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigsRequest
     */
    selectedExperiments: Array<string>;
}

/**
 * Check if a given object implements the ConfigsRequest interface.
 */
export function instanceOfConfigsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "selectedSystems" in value;
    isInstance = isInstance && "selectedExperiments" in value;

    return isInstance;
}

export function ConfigsRequestFromJSON(json: any): ConfigsRequest {
    return ConfigsRequestFromJSONTyped(json, false);
}

export function ConfigsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'selectedSystems': ((json['selectedSystems'] as Array<any>).map(SystemRefFromJSON)),
        'selectedExperiments': json['selectedExperiments'],
    };
}

export function ConfigsRequestToJSON(value?: ConfigsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'selectedSystems': ((value.selectedSystems as Array<any>).map(SystemRefToJSON)),
        'selectedExperiments': value.selectedExperiments,
    };
}

