/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Input
 */
export interface Input {
    /**
     * 
     * @type {number}
     * @memberof Input
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Input
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Input
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Input
     */
    unit: string;
    /**
     * 
     * @type {number}
     * @memberof Input
     */
    cardinality: number;
}

/**
 * Check if a given object implements the Input interface.
 */
export function instanceOfInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "unit" in value;
    isInstance = isInstance && "cardinality" in value;

    return isInstance;
}

export function InputFromJSON(json: any): Input {
    return InputFromJSONTyped(json, false);
}

export function InputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Input {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'title': json['title'],
        'unit': json['unit'],
        'cardinality': json['cardinality'],
    };
}

export function InputToJSON(value?: Input | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'title': value.title,
        'unit': value.unit,
        'cardinality': value.cardinality,
    };
}

