/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PathRequest
 */
export interface PathRequest {
    /**
     * 
     * @type {string}
     * @memberof PathRequest
     */
    path: string;
}

/**
 * Check if a given object implements the PathRequest interface.
 */
export function instanceOfPathRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "path" in value;

    return isInstance;
}

export function PathRequestFromJSON(json: any): PathRequest {
    return PathRequestFromJSONTyped(json, false);
}

export function PathRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PathRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': json['path'],
    };
}

export function PathRequestToJSON(value?: PathRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
    };
}

