/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulationConfig
 */
export interface SimulationConfig {
    /**
     * 
     * @type {number}
     * @memberof SimulationConfig
     */
    numberOfExecutions: number;
    /**
     * 
     * @type {string}
     * @memberof SimulationConfig
     */
    logFileSimulation: string;
    /**
     * 
     * @type {string}
     * @memberof SimulationConfig
     */
    configurations: string;
    /**
     * 
     * @type {string}
     * @memberof SimulationConfig
     */
    results: string;
}

/**
 * Check if a given object implements the SimulationConfig interface.
 */
export function instanceOfSimulationConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "numberOfExecutions" in value;
    isInstance = isInstance && "logFileSimulation" in value;
    isInstance = isInstance && "configurations" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function SimulationConfigFromJSON(json: any): SimulationConfig {
    return SimulationConfigFromJSONTyped(json, false);
}

export function SimulationConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulationConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numberOfExecutions': json['numberOfExecutions'],
        'logFileSimulation': json['logFileSimulation'],
        'configurations': json['configurations'],
        'results': json['results'],
    };
}

export function SimulationConfigToJSON(value?: SimulationConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'numberOfExecutions': value.numberOfExecutions,
        'logFileSimulation': value.logFileSimulation,
        'configurations': value.configurations,
        'results': value.results,
    };
}

