/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemRef
 */
export interface SystemRef {
    /**
     * 
     * @type {string}
     * @memberof SystemRef
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SystemRef
     */
    file: string;
}

/**
 * Check if a given object implements the SystemRef interface.
 */
export function instanceOfSystemRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function SystemRefFromJSON(json: any): SystemRef {
    return SystemRefFromJSONTyped(json, false);
}

export function SystemRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'file': json['file'],
    };
}

export function SystemRefToJSON(value?: SystemRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'file': value.file,
    };
}

