/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyPath200Response
 */
export interface VerifyPath200Response {
    /**
     * 
     * @type {boolean}
     * @memberof VerifyPath200Response
     */
    ok?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VerifyPath200Response
     */
    realPath?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VerifyPath200Response
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the VerifyPath200Response interface.
 */
export function instanceOfVerifyPath200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VerifyPath200ResponseFromJSON(json: any): VerifyPath200Response {
    return VerifyPath200ResponseFromJSONTyped(json, false);
}

export function VerifyPath200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPath200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': !exists(json, 'ok') ? undefined : json['ok'],
        'realPath': !exists(json, 'realPath') ? undefined : json['realPath'],
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
    };
}

export function VerifyPath200ResponseToJSON(value?: VerifyPath200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'realPath': value.realPath,
        'empty': value.empty,
    };
}

