const { VITE_ENVIRONMENT, VITE_API_DEV_URL, VITE_API_LOCAL_URL, VITE_TEST_REACT } = import.meta.env;

export {
    VITE_ENVIRONMENT,
    VITE_API_DEV_URL,
    VITE_API_LOCAL_URL,
    VITE_TEST_REACT
};