/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ComponentUI,
  Error400,
  Error500,
} from '../models';
import {
    ComponentUIFromJSON,
    ComponentUIToJSON,
    Error400FromJSON,
    Error400ToJSON,
    Error500FromJSON,
    Error500ToJSON,
} from '../models';

/**
 * 
 */
export class ComponentsApi extends runtime.BaseAPI {

    /**
     * Fetch an array of component objects
     * Retrieve a list of components
     */
    async apiComponentsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ComponentUI>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/components`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ComponentUIFromJSON));
    }

    /**
     * Fetch an array of component objects
     * Retrieve a list of components
     */
    async apiComponentsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ComponentUI>> {
        const response = await this.apiComponentsGetRaw(initOverrides);
        return await response.value();
    }

}
