/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Default200Response,
  Error404,
  PathRequest,
} from '../models';
import {
    Default200ResponseFromJSON,
    Default200ResponseToJSON,
    Error404FromJSON,
    Error404ToJSON,
    PathRequestFromJSON,
    PathRequestToJSON,
} from '../models';

export interface DeleteInformationRequest {
    pathRequest: PathRequest;
}

/**
 * 
 */
export class DeleteInformationApi extends runtime.BaseAPI {

    /**
     * Delete data of selected folder it selected
     * Detele information of given folder
     */
    async deleteInformationRaw(requestParameters: DeleteInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Default200Response>> {
        if (requestParameters.pathRequest === null || requestParameters.pathRequest === undefined) {
            throw new runtime.RequiredError('pathRequest','Required parameter requestParameters.pathRequest was null or undefined when calling deleteInformation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/delete-information`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PathRequestToJSON(requestParameters.pathRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Default200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete data of selected folder it selected
     * Detele information of given folder
     */
    async deleteInformation(requestParameters: DeleteInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Default200Response> {
        const response = await this.deleteInformationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
