/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Default200Response,
  Error400,
  Error500,
  SelectedExperimentsRequest,
} from '../models';
import {
    Default200ResponseFromJSON,
    Default200ResponseToJSON,
    Error400FromJSON,
    Error400ToJSON,
    Error500FromJSON,
    Error500ToJSON,
    SelectedExperimentsRequestFromJSON,
    SelectedExperimentsRequestToJSON,
} from '../models';

export interface ApiExportToSimulationsPostRequest {
    selectedExperimentsRequest: SelectedExperimentsRequest;
}

/**
 * 
 */
export class ExportToSimulationApi extends runtime.BaseAPI {

    /**
     * send the selected IDs to the pcm simulation manager and launch the conversion process, once this has finished all the results will be stored on the pcm-results folder
     * execute pcm simulation manager and store the results
     */
    async apiExportToSimulationsPostRaw(requestParameters: ApiExportToSimulationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Default200Response>> {
        if (requestParameters.selectedExperimentsRequest === null || requestParameters.selectedExperimentsRequest === undefined) {
            throw new runtime.RequiredError('selectedExperimentsRequest','Required parameter requestParameters.selectedExperimentsRequest was null or undefined when calling apiExportToSimulationsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/exportToSimulations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelectedExperimentsRequestToJSON(requestParameters.selectedExperimentsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Default200ResponseFromJSON(jsonValue));
    }

    /**
     * send the selected IDs to the pcm simulation manager and launch the conversion process, once this has finished all the results will be stored on the pcm-results folder
     * execute pcm simulation manager and store the results
     */
    async apiExportToSimulationsPost(requestParameters: ApiExportToSimulationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Default200Response> {
        const response = await this.apiExportToSimulationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
