/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Boolean200Response,
  Error400,
  Error500,
} from '../models';
import {
    Boolean200ResponseFromJSON,
    Boolean200ResponseToJSON,
    Error400FromJSON,
    Error400ToJSON,
    Error500FromJSON,
    Error500ToJSON,
} from '../models';

/**
 * 
 */
export class IsSimulationRunningApi extends runtime.BaseAPI {

    /**
     * checks if opSimulationManager process is running
     * check if there is opSimulationManager is running
     */
    async apiIsSimulationRunningGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Boolean200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/isSimulationRunning`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Boolean200ResponseFromJSON(jsonValue));
    }

    /**
     * checks if opSimulationManager process is running
     * check if there is opSimulationManager is running
     */
    async apiIsSimulationRunningGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Boolean200Response> {
        const response = await this.apiIsSimulationRunningGetRaw(initOverrides);
        return await response.value();
    }

}
