/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Default200Response,
  Error400,
  Error500,
  PathRequest,
} from '../models';
import {
    Default200ResponseFromJSON,
    Default200ResponseToJSON,
    Error400FromJSON,
    Error400ToJSON,
    Error500FromJSON,
    Error500ToJSON,
    PathRequestFromJSON,
    PathRequestToJSON,
} from '../models';

export interface ApiPathToConvertedCasesPostRequest {
    pathRequest: PathRequest;
}

/**
 * 
 */
export class PathToConvertedCasesApi extends runtime.BaseAPI {

    /**
     * specify where all the selected experiments will be stored afther the conversion is done
     * path to save the selected PCM converted cases
     */
    async apiPathToConvertedCasesPostRaw(requestParameters: ApiPathToConvertedCasesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Default200Response>> {
        if (requestParameters.pathRequest === null || requestParameters.pathRequest === undefined) {
            throw new runtime.RequiredError('pathRequest','Required parameter requestParameters.pathRequest was null or undefined when calling apiPathToConvertedCasesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/pathToConvertedCases`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PathRequestToJSON(requestParameters.pathRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Default200ResponseFromJSON(jsonValue));
    }

    /**
     * specify where all the selected experiments will be stored afther the conversion is done
     * path to save the selected PCM converted cases
     */
    async apiPathToConvertedCasesPost(requestParameters: ApiPathToConvertedCasesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Default200Response> {
        const response = await this.apiPathToConvertedCasesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
