/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Error400,
  Error500,
  SystemUI,
} from '../models';
import {
    Error400FromJSON,
    Error400ToJSON,
    Error500FromJSON,
    Error500ToJSON,
    SystemUIFromJSON,
    SystemUIToJSON,
} from '../models';

/**
 * 
 */
export class SystemsApi extends runtime.BaseAPI {

    /**
     * Fetch an array of system objects
     * Retrieve a list of systems
     */
    async apiSystemsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SystemUI>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/systems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SystemUIFromJSON));
    }

    /**
     * Fetch an array of system objects
     * Retrieve a list of systems
     */
    async apiSystemsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SystemUI>> {
        const response = await this.apiSystemsGetRaw(initOverrides);
        return await response.value();
    }

}
