/* tslint:disable */
/* eslint-disable */
/**
 * opGUI - OpenAPI 3.0
 * Dummy description about the available endpoints Some useful links: - [The opGUI repository](https://gitlab.eclipse.org/eclipse/openpass/opgui) - [The documentation page](https://www.eclipse.org/openpass/content/html/index.html)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Error404,
  Error500,
  PathRequest,
  VerifyPath200Response,
} from '../models';
import {
    Error404FromJSON,
    Error404ToJSON,
    Error500FromJSON,
    Error500ToJSON,
    PathRequestFromJSON,
    PathRequestToJSON,
    VerifyPath200ResponseFromJSON,
    VerifyPath200ResponseToJSON,
} from '../models';

export interface VerifyPathRequest {
    pathRequest: PathRequest;
}

/**
 * 
 */
export class VerifyPathApi extends runtime.BaseAPI {

    /**
     * Verify if a specified path exists and contains data
     * Verify if a path exists and has data
     */
    async verifyPathRaw(requestParameters: VerifyPathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyPath200Response>> {
        if (requestParameters.pathRequest === null || requestParameters.pathRequest === undefined) {
            throw new runtime.RequiredError('pathRequest','Required parameter requestParameters.pathRequest was null or undefined when calling verifyPath.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/verify-path`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PathRequestToJSON(requestParameters.pathRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyPath200ResponseFromJSON(jsonValue));
    }

    /**
     * Verify if a specified path exists and contains data
     * Verify if a path exists and has data
     */
    async verifyPath(requestParameters: VerifyPathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyPath200Response> {
        const response = await this.verifyPathRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
